import * as React from 'react';
import {
	IconAlertOctagon,
	IconAlertTriangle,
	IconArchive,
	IconArrowBack,
	IconArrowBackUp,
	IconArrowForward,
	IconArrowUpRight,
	IconArrowsSort,
	IconAward,
	IconBinaryTree,
	IconBook,
	IconBox,
	IconBraces,
	IconBug,
	IconCheck,
	IconChevronDown,
	IconChevronRight,
	IconCircle,
	IconCircleCheck,
	IconCircleDashed,
	IconCircleDot,
	IconClock,
	IconCommand,
	IconComponents,
	IconCopy,
	IconDatabase,
	IconDownload,
	IconDots,
	IconEdit,
	IconEyeglass,
	IconFileCode,
	IconFileImport,
	IconFileText,
	IconFileZip,
	IconFiles,
	IconFocus2,
	IconFolder,
	IconFolderPlus,
	IconGitBranch,
	IconGridDots,
	IconHash,
	IconHome,
	IconInfoCircle,
	IconLayoutBottombarCollapse,
	IconLayoutBottombarExpand,
	IconLayoutColumns,
	IconLayoutGrid,
	IconLayoutSidebarLeftCollapse,
	IconLayoutSidebarLeftExpand,
	IconLayoutSidebarRightCollapse,
	IconLayoutSidebarRightExpand,
	IconListDetails,
	IconLink,
	IconMarquee,
	IconMarqueeOff,
	IconMinus,
	IconPackage,
	IconPackgeExport,
	IconPhoto,
	IconPhotoOff,
	IconPlayerPlay,
	IconPlus,
	IconPuzzle,
	IconRefresh,
	IconRocket,
	IconSearch,
	IconSettings,
	IconSquare,
	IconStar,
	IconTag,
	IconTags,
	IconTerminal2,
	IconTool,
	IconTrash,
	IconUnlink,
	IconUpload,
	IconVariable,
	IconWriting,
	IconX
} from '@tabler/icons';

export interface TablerIconProps {
	className?: string;
	icon: string;
	size?: number | string;
	stroke?: number | string;
}

const iconRegistry: Record<string, typeof IconCircle> = {
	'alert-octagon': IconAlertOctagon,
	'alert-triangle': IconAlertTriangle,
	archive: IconArchive,
	'arrow-back': IconArrowBack,
	'arrow-back-up': IconArrowBackUp,
	'arrow-forward': IconArrowForward,
	'arrow-up-right': IconArrowUpRight,
	'arrows-sort': IconArrowsSort,
	award: IconAward,
	'binary-tree': IconBinaryTree,
	book: IconBook,
	box: IconBox,
	braces: IconBraces,
	bug: IconBug,
	check: IconCheck,
	'chevron-down': IconChevronDown,
	'chevron-right': IconChevronRight,
	circle: IconCircle,
	'circle-check': IconCircleCheck,
	'circle-dashed': IconCircleDashed,
	'circle-dot': IconCircleDot,
	clock: IconClock,
	command: IconCommand,
	components: IconComponents,
	copy: IconCopy,
	database: IconDatabase,
	download: IconDownload,
	dots: IconDots,
	edit: IconEdit,
	eyeglass: IconEyeglass,
	'file-code': IconFileCode,
	'file-import': IconFileImport,
	'file-text': IconFileText,
	'file-zip': IconFileZip,
	files: IconFiles,
	'focus-2': IconFocus2,
	folder: IconFolder,
	'folder-open': IconFolder,
	'folder-plus': IconFolderPlus,
	'git-branch': IconGitBranch,
	'grid-dots': IconGridDots,
	hash: IconHash,
	home: IconHome,
	'info-circle': IconInfoCircle,
	'layout-bottombar-collapse': IconLayoutBottombarCollapse,
	'layout-bottombar-expand': IconLayoutBottombarExpand,
	'layout-columns': IconLayoutColumns,
	'layout-grid': IconLayoutGrid,
	'layout-sidebar-left-collapse': IconLayoutSidebarLeftCollapse,
	'layout-sidebar-left-expand': IconLayoutSidebarLeftExpand,
	'layout-sidebar-right-collapse': IconLayoutSidebarRightCollapse,
	'layout-sidebar-right-expand': IconLayoutSidebarRightExpand,
	'list-details': IconListDetails,
	link: IconLink,
	marquee: IconMarquee,
	'marquee-off': IconMarqueeOff,
	minus: IconMinus,
	package: IconPackage,
	// @tabler/icons 1.x ships this export with the historical misspelling.
	'package-export': IconPackgeExport,
	photo: IconPhoto,
	'photo-off': IconPhotoOff,
	'player-play': IconPlayerPlay,
	plus: IconPlus,
	'point-filled': IconCircleDot,
	puzzle: IconPuzzle,
	refresh: IconRefresh,
	rocket: IconRocket,
	search: IconSearch,
	settings: IconSettings,
	square: IconSquare,
	star: IconStar,
	tag: IconTag,
	tags: IconTags,
	'terminal-2': IconTerminal2,
	tool: IconTool,
	trash: IconTrash,
	unlink: IconUnlink,
	upload: IconUpload,
	variable: IconVariable,
	writing: IconWriting,
	x: IconX
};

export const TablerIcon: React.FC<TablerIconProps> = ({
	className,
	icon,
	size = '1em',
	stroke = 1.75
}) => {
	const Icon = iconRegistry[icon] ?? IconCircle;

	return (
		<Icon
			aria-hidden
			className={className}
			data-icon-name={icon}
			focusable="false"
			size={size}
			stroke={stroke}
		/>
	);
};
