// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphFocus } from "./CoreGraphFocus";
import type { CoreLinkLayerOptions } from "./CoreLinkLayerOptions";
import type { CoreRect } from "./CoreRect";

export type CoreGraphProjectionOptions = { focus: CoreGraphFocus | null, layers: CoreLinkLayerOptions, viewport: CoreRect | null, };
