// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSearchScope } from "./CoreSearchScope";

export type CoreSearchHit = { excerpt: string, line: number, scope: CoreSearchScope, sourceId: string, sourceName: string, start: number, };
