// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreSourceKind } from "./CoreSourceKind";

export type CoreSourceFile = { characterCount: number, id: string, kind: CoreSourceKind, lineCount: number, name: string, passageId: string | null, tags: Array<string>, };
