// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphEdgeKind } from "./CoreGraphEdgeKind";
import type { CoreRect } from "./CoreRect";

export type CoreGraphEdge = { kind: CoreGraphEdgeKind, sourceBounds: CoreRect, sourceId: string, targetBounds: CoreRect | null, targetId: string | null, targetName: string, };
