// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDiagnosticSeverity } from "./CoreDiagnosticSeverity";

export type CoreDiagnostic = { code: string, message: string, passageId: string | null, severity: CoreDiagnosticSeverity, sourceId: string, };
