// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreAssetPublishRule } from "./CoreAssetPublishRule";
import type { CoreAssetReference } from "./CoreAssetReference";
import type { CoreAssetSnippet } from "./CoreAssetSnippet";

export type CoreAssetInventoryEntry = { durationMs: number | null, exists: boolean | null, height: number | null, kind: string, missing: boolean, modifiedAt: string | null, normalizedPath: string, path: string, previewUrl: string | null, publish: CoreAssetPublishRule, referenceCount: number, references: Array<CoreAssetReference>, sizeBytes: number | null, snippet: CoreAssetSnippet, thumbnailUrl: string | null, unused: boolean, width: number | null, };
