// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphEdge } from "./CoreGraphEdge";
import type { CoreGraphLayoutState } from "./CoreGraphLayoutState";
import type { CoreGraphNode } from "./CoreGraphNode";
import type { CoreGraphStats } from "./CoreGraphStats";
import type { CoreRect } from "./CoreRect";

export type CoreGraphProjection = { bounds: CoreRect | null, edges: Array<CoreGraphEdge>, layoutState: CoreGraphLayoutState, nodes: Array<CoreGraphNode>, stats: CoreGraphStats, };
