// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreDiagnostic } from "./CoreDiagnostic";
import type { CoreGraphStats } from "./CoreGraphStats";
import type { CoreSearchHit } from "./CoreSearchHit";
import type { CoreSourceFile } from "./CoreSourceFile";

export type CoreStoryIndex = { diagnostics: Array<CoreDiagnostic>, files: Array<CoreSourceFile>, graph: CoreGraphStats, searchHits: Array<CoreSearchHit>, storyId: string, tags: Array<string>, };
