// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphDirection } from "./CoreGraphDirection";

export type CoreGraphFocus = { direction: CoreGraphDirection, passageIds: Array<string>, radius: number, };
