// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CoreGraphStats = { brokenLinks: number, emptyPassages: number, links: number, orphanPassages: number, passages: number, resolvedLinks: number, selfLinks: number, taggedPassages: number, unreachablePassages: number, };
