// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreRect } from "./CoreRect";

export type PassageSnapshot = { id: string, layout: CoreRect | null, name: string, storyId: string, tags: Array<string>, text: string, };
