// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreRect } from "./CoreRect";

export type PassagePatch = { layout: CoreRect | null, name: string | null, tags: Array<string> | null, text: string | null, };
