// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreRect } from "./CoreRect";

export type PassageMove = { passageId: string, bounds: CoreRect, };
