// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CoreGraphProjection } from "./CoreGraphProjection";
import type { CoreStoryIndex } from "./CoreStoryIndex";
import type { PassagePatch } from "./PassagePatch";
import type { PassageSnapshot } from "./PassageSnapshot";
import type { ProjectSnapshot } from "./ProjectSnapshot";

export type Patch = { "type": "dirtyStateChanged", dirty: boolean, } | { "type": "graphProjectionUpdated", projection: CoreGraphProjection, story_id: string, } | { "type": "layoutSaved", projection: CoreGraphProjection, story_id: string, } | { "type": "passageCreated", passage: PassageSnapshot, story_id: string, } | { "type": "passageDeleted", passage_id: string, story_id: string, } | { "type": "passageUpdated", changes: PassagePatch, passage_id: string, story_id: string, } | { "type": "projectSnapshotReplaced", snapshot: ProjectSnapshot, } | { "type": "startPassageChanged", passage_id: string, story_id: string, } | { "type": "storyIndexUpdated", index: CoreStoryIndex, story_id: string, } | { "type": "storyScriptUpdated", script: string, story_id: string, } | { "type": "storyStylesheetUpdated", story_id: string, stylesheet: string, };
