// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorySnapshot } from "./StorySnapshot";

export type ProjectSnapshot = { dirty: boolean, name: string, schemaVersion: number, stories: Array<StorySnapshot>, };
